### ISSUE TITLE
Negative numbers not being recognized properly

### ISSUE THREAD

**Issue by brookescott87** [maziac/hex-hover-converter#4]
It seems that negative decimal numbers are not being recognized as such, for example:

![image](https://user-images.githubusercontent.com/42704084/116722159-12cfa800-a9ac-11eb-9a39-eba01e3a8808.png)

I expected to see the hex value `EFFFFFFF` here, rather than `10000001`.

**Comment by maziac** [comment]
Actually the negative number is there but I was also confused when I tested it.
The problem is that you see it on the right side but you have to scroll, i.e. see here:
![Bildschirmfoto 2021-04-30 um 19 24 06](https://user-images.githubusercontent.com/3081973/116731351-dd49af80-a9e9-11eb-8806-a19c7791e162.jpg)

But, of course, this is not a good solution.
Maybe I will remove the binary conversion in this case because it makes the window too wide for large numbers.

**Comment by maziac** [comment]
Could you please try this pre-release:
https://github.com/maziac/hex-hover-converter/releases/tag/v1.2.1

Still scrolling is required (there is little modification possible to the vscode markdown unfortunately).
But I changed the order, ie. if it is a negative number it is shown in the first column.
