### ISSUE TITLE
‘#x’ hex format

### ISSUE THREAD

**Issue by formicant** [maziac/hex-hover-converter#5]
Please consider supporting the ‘#x’ hex format.
E. g.:
```
    addr EQU #1234 ; = 4660 dec
    ld a, #FF      ; =  255 dec
```

The ‘#’ character is a valid prefix for hexadecimal numbers in SjASMPlus and some other Z80 assembly dialects.
[SjASMPlus docs. Numeric constants](https://z00m128.github.io/sjasmplus/documentation.html#c_constants)

**Comment by maziac** [comment]
Actually the hex conversion is shown, see here:
![Bildschirmfoto 2021-05-11 um 18 26 55](https://user-images.githubusercontent.com/3081973/117851326-7bf5cc00-b286-11eb-8564-16bfb9ed923d.jpg)


It shows both interpreting the number as decimal **and** as hexadecimal.

The reason is that I want to keep the parsing simple to catch as many formats as possible.
Therefore I only use the very common $, 0x prefix and the suffix h to recognize a hex number.
 <code>#</code> is not so common.
E.g. in xml a &#8217 interprets the 8217 as **decimal** value.

I thinks displaying both possibilities is the better option.

**Comment by nwehrle** [comment]
I really like how you handle #1234, because it means decimal 1234 for my usecase. #$1234 will be interpreted as HEX for my usecase (ca65).
